config/routes.rb
Rails.application.routes.draw do
  resources :merchants
  devise_for :users
  resources :users
  get 'home', to: 'home#index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  serialize :preferences, HashSerializer
  store_accessor :extra_info, :phone_number, :website
  validates :name, presence: true, length: { minimum: 3}, uniqueness: { case_sensitive: false }
  validates :city, presence: true
  validates :street, presence: true
  validates :country_code, presence: true, numericality: { only_integer: true }, length: { in: 5..9 }

  def self.search(search)
    if search
      merchant_name = Merchant.find_by(name: search)
      if merchant_name
        where(id: merchant_name)
      else
        @merchants = Merchant.order(id: :desc)
      end
    else
      @merchants = Merchant.order(id: :asc)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :merchants
  enum role: {
    user: 0,
    admin: 1
  }, _prefix: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_merchant, only: %i[show edit update destroy]

  # GET /merchants or /merchants.json
  def index
    @merchants = Merchant.search(params[:search])
  end

  # GET /merchants/1 or /merchants/1.json
  def show; end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
    if current_user.role_admin?
      @merchant = Merchant.find_by_id(params[:id])
    else
      redirect_to @merchant, alert: 'Admin not authrized'
    end
  end

  # POST /merchants or /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to merchants_url(@merchants), notice: 'Merchant was successfully created.' }
        format.json { render :index, status: :created, location: @merchants }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1 or /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to merchants_url(@merchants), notice: 'Merchant was successfully updated.' }
        format.json { render :index, status: :ok, location: @merchants }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1 or /merchants/1.json
  def destroy
    if current_user.role_admin?
      @merchant.destroy

      respond_to do |format|
        format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to merchants_url, alert: 'Admin not authrized'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_merchant
    @merchant = Merchant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def merchant_params
    params.require(:merchant).permit(:name, :city, :street, :country_code, :extra_info)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.order(role: :asc, id: :asc)
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    if current_user.role_admin?
      @user = User.find_by_id(params[:id])
    else
      redirect_to @user, alert: 'Admin not authrized'
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user.role_admin?
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to users_url, alert: 'Admin not authrized'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:nickname, :email, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1 class="text-center">Welcome 
<% if user_signed_in? %>
<small class="text-muted"><%= current_user.role %></small> : <em><%= current_user.nickname %></em> - <mark><%= current_user.email %></mark>
<% end %>
to Merchants</h1>
<div class="mx-auto" style="width: 50%;">
<%= image_tag 'merchants', height: '100%', width: '100%'%>
</div>
<p class="text-center">You need to login or register before proceeding.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Merchants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/438a14ad7f.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/merchants/_form.html.erb
<%= form_with(model: merchant) do |form| %>
  <% if merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
        <% merchant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Name", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, placeholder: "City", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, placeholder: "Street", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :country_code %>
    <%= form.text_field :country_code, placeholder: "Country Code", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :extra_info %>
    <%= form.text_field :extra_info, placeholder: "Country Code", class: "form-control" %>
  </div>

  <div class="actions">
    <button type="submit" class="btn btn-outline-success">Save </button>
    <%= link_to 'Back', merchants_path, class: "btn btn-outline-info" %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing Merchant</h1>

<%= render 'form', merchant: @merchant %>

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merchants</h1>
<h4>Search by Merchants</h4>
  <%= form_tag merchants_path, method: :get  do%>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag ("Search")%>
  <% end %>
<%= link_to 'New Merchant', new_merchant_path, class: 'btn btn-primary' %>

<table class="table table-success table-striped table-hover table-borderless">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Street</th>
      <th>Country code</th>
      <th>Extra info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= link_to merchant.name, merchant %></td>
        <td><%= merchant.city %></td>
        <td><%= merchant.street %></td>
        <td><%= merchant.country_code %></td>
        <td><%= merchant.extra_info %></td>
        <td>
          <%= link_to  edit_merchant_path(merchant) do %>
            <i class="fas fa-pencil-alt"></i>
          <% end %>
        </td>
        <td><%= link_to merchant, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="fas fa-trash-alt"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/merchants/new.html.erb
<h1>New Merchant</h1>

<%= render 'form', merchant: @merchant %>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @merchant.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @merchant.city %>
</p>

<p>
  <strong>Street:</strong>
  <%= @merchant.street %>
</p>

<p>
  <strong>Country code:</strong>
  <%= @merchant.country_code %>
</p>

<p>
  <strong>Extra info:</strong>
  <%= @merchant.extra_info %>
</p>

<%= link_to 'Edit', edit_merchant_path(@merchant), class: 'btn btn-outline-warning' %> |
<%= link_to 'Back', merchants_path, class: 'btn btn-outline-info' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Merchants home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/merchants">Merchants List</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/users">Users List</a>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %> 
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path, class: 'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class: 'nav-link'%>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <%= text_field_tag :search, params[:search], placeholder: "Search Merchants" %>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, placeholder: "NickName", class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, placeholder: "email", class: "form-control" %>
  </div>
  <% if current_user.role_admin? %>
    <%= form.label :role %>
    <%= form.select :role, [["User", "user"], ["Admin", "admin"]] %>
  <% end %>
  <br />
  <br>
  <button type="submit" class="btn btn-primary">Save </button>
  <%= link_to "Open User List", users_path, class: "btn btn-info" %>
  <%= link_to 'Account Settings', edit_user_registration_path, class: "btn btn-secondary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped table-dark table-hover">
  <thead>
    <tr>
      <th>NickName</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td>
          <%= link_to edit_user_path(user) do %>
            <i class="fas fa-edit"></i>
          <% end %>
        </td>
        <td>
          <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fas fa-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>NickName:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-warning" %> |
<%= link_to 'Back', users_path, class: 'btn btn-info'%>